<?php

namespace DFSClientV3\Models\OnPageApi\Lighthouse;

use DFSClientV3\Entity\Custom\OnPageLighthouseLanguagesEntityMain;
use DFSClientV3\Models\AbstractModel;

class OnPageLighthouseLanguages extends AbstractModel
{
    protected $method = 'GET';
    protected $isSupportedMerge = true;
    protected $pathToMainData = 'tasks->0->result';
    protected $requestToFunction = 'on_page/lighthouse/languages';

    /**
     * @return OnPageLighthouseLanguagesEntityMain
     */
    public function get(): OnPageLighthouseLanguagesEntityMain
    {
        return parent::get();
    }

    /**
     * @param array $modelPool
     * @throws \Exception
     */
    public static function getAfterMerge(array $modelPool)
    {
        return parent::getAfterMerge($modelPool); // TODO: Change the autogenerated stub
    }
}
