<?php


namespace DFSClientV3\Models\MerchantApi\Amazon\Sellers;


use DFSClientV3\Models\AbstractModel;

class AmazonSellersLiveAdvanced extends AbstractModel
{
    protected $method = 'POST';
    protected $isSupportedMerge = true;
    protected $pathToMainData = 'tasks->{$postID}->result';
    protected $requestToFunction = 'merchant/amazon/sellers/live/advanced';
    protected $resultShouldBeTransformedToArray = true;

    /**
     * @return \DFSClientV3\Entity\Custom\AmazonSellersLiveAdvancedEntityMain
     */
    public function get(): \DFSClientV3\Entity\Custom\AmazonSellersLiveAdvancedEntityMain
    {
        return parent::get();
    }

	/**
	 * @param string $asin
	 * @return $this
	 */
	public function setAsin(string $asin)
	{
		$this->payload['asin'] = $asin;
		return $this;
	}

	/**
     * @param string $locationName
     * @return $this
     */
    public function setLocationName(string $locationName)
    {
        $this->payload['location_name'] = $locationName;

        return $this;
    }

    /**
     * @param int $locationCode
     * @return $this
     */
    public function setLocationCode(int $locationCode)
    {
        $this->payload['location_code'] = $locationCode;
        return $this;
    }

    /**
     * @param string $locationCoordinate
     * @return $this
     */
    public function setLocationCoordinate(string $locationCoordinate)
    {
        $this->payload['location_coordinate'] = $locationCoordinate;
        return $this;
    }

    /**
     * @param string $languageName
     * @return $this
     */
    public function setLanguageName(string $languageName)
    {
        $this->payload['language_name'] = $languageName;
        return $this;
    }

    /**
     * @param string $langCode
     * @return $this
     */
    public function setLanguageCode(string $langCode)
    {
        $this->payload['language_code'] = $langCode;

        return $this;
    }

	/**
	 * @param string $seDomain
	 * @return $this
	 */
	public function setSeDomain(string $seDomain)
	{
		$this->payload['se_domain'] = $seDomain;
		return $this;
	}

    /**
     * @param string $tag
     * @return $this
     */
    public function setTag(string $tag)
    {
        $this->payload['tag'] = $tag;
        return $this;
    }

    /**
     * @param array $modelPool
     * @return array
     * @throws \Exception
     */
    public static function getAfterMerge(array $modelPool)
    {
        return parent::getAfterMerge($modelPool); // TODO: Change the autogenerated stub
    }
}
