<?php

namespace DFSClientV3\Models\DomainAnalyticsApi\Similarweb;

use DFSClientV3\Models\AbstractModel;

class SimilarwebSetTask extends AbstractModel {
	protected $method = 'POST';
	protected $isSupportedMerge = true;
	protected $pathToMainData = 'tasks->{$postID}->result';
	protected $requestToFunction = 'domain_analytics/similarweb/task_post';
	protected $resultShouldBeTransformedToArray = true;

	/**
	 * @return \DFSClientV3\Entity\Custom\SimilarwebSetTaskEntityMain
	 */
	public function get(): \DFSClientV3\Entity\Custom\SimilarwebSetTaskEntityMain {
		return parent::get();
	}

	/**
	 * @param string $target
	 * @return $this
	 */
	public function setTarget(string $target) {
		$this->payload['target'] = $target;

		return $this;
	}

	/**
	 * @param string $tag
	 * @return $this
	 */
	public function setTag(string $tag) {
		$this->payload['tag'] = $tag;
		return $this;
	}

	/**
	 * @param string $postbackUrl
	 * @return $this
	 */
	public function setPostbackUrl(string $postbackUrl) {
		$this->payload['postback_url'] = $postbackUrl;
		return $this;
	}

	/**
	 * @param string $pingbackUrl
	 * @return $this
	 */
	public function setPingbackUrl(string $pingbackUrl) {
		$this->payload['pingback_url'] = $pingbackUrl;
		return $this;
	}

	/**
	 * @param array $modelPool
	 * @return array
	 * @throws \Exception
	 */
	public static function getAfterMerge(array $modelPool) {
		return parent::getAfterMerge($modelPool); // TODO: Change the autogenerated stub
	}

}
