<?php


namespace DFSClientV3\Models\AppDataApi\Google\AppInfo;


use DFSClientV3\Models\AbstractModel;

class GoogleAppInfoSetTask extends AbstractModel
{
	protected $method = 'POST';
	protected $isSupportedMerge = true;
	protected $pathToMainData = 'tasks->{$postID}->result';
	protected $requestToFunction = 'app_data/google/app_info/task_post';
	protected $resultShouldBeTransformedToArray = true;

	/**
	 * @return \DFSClientV3\Entity\Custom\GoogleAppInfoSetTaskEntityMain
	 */
	public function get(): \DFSClientV3\Entity\Custom\GoogleAppInfoSetTaskEntityMain
	{
		return parent::get();
	}

	/**
	 * @param string $app_id
	 * @return $this
	 */
	public function setAppId(string $app_id)
	{
		$this->payload['app_id'] = $app_id;
		return $this;
	}

	/**
	 * @param int $priority
	 * @return $this
	 */
	public function setPriority(int $priority)
	{
		$this->payload['priority'] = $priority;
		return $this;
	}

	/**
	 * @param string $locationName
	 * @return $this
	 */
	public function setLocationName(string $locationName)
	{
		$this->payload['location_name'] = $locationName;

		return $this;
	}

	/**
	 * @param int $locationCode
	 * @return $this
	 */
	public function setLocationCode(int $locationCode)
	{
		$this->payload['location_code'] = $locationCode;
		return $this;
	}

	/**
	 * @param string $locationCoordinate
	 * @return $this
	 */
	public function setLocationCoordinate(string $locationCoordinate)
	{
		$this->payload['location_coordinate'] = $locationCoordinate;
		return $this;
	}

	/**
	 * @param string $languageName
	 * @return $this
	 */
	public function setLanguageName(string $languageName)
	{
		$this->payload['language_name'] = $languageName;
		return $this;
	}

	/**
	 * @param string $langCode
	 * @return $this
	 */
	public function setLanguageCode(string $langCode)
	{
		$this->payload['language_code'] = $langCode;

		return $this;
	}

	/**
	 * @param string $tag
	 * @return $this
	 */
	public function setTag(string $tag)
	{
		$this->payload['tag'] = $tag;
		return $this;
	}

	/**
	 * @param string $postbackUrl
	 * @return $this
	 */
	public function setPostbackUrl(string $postbackUrl)
	{
		$this->payload['postback_url'] = $postbackUrl;
		return $this;
	}

	/**
	 * @param string $pingbackUrl
	 * @return $this
	 */
	public function setPingbackUrl(string $pingbackUrl)
	{
		$this->payload['pingback_url'] = $pingbackUrl;
		return $this;
	}

	/**
	 * @param array $modelPool
	 * @return array
	 * @throws \Exception
	 */
	public static function getAfterMerge(array $modelPool)
	{
		return parent::getAfterMerge($modelPool); // TODO: Change the autogenerated stub
	}
}
