<?php

namespace DFSClientV3\Models\ContentGenerationApi;

use DFSClientV3\Entity\Custom\ContentGenerationGenerateSubTopicsLiveEntityMain;
use DFSClientV3\Entity\Custom\ContentGenerationGenerateTextLiveEntityMain;
use DFSClientV3\Models\AbstractModel;

class ContentGenerationGenerateSubTopicsLive extends AbstractModel
{
    protected $method = 'POST';

    protected $isSupportedMerge = true;

    protected $pathToMainData = 'tasks->{$postID}->result';

    protected $requestToFunction = 'content_generation/generate_sub_topics/live';

    protected $resultShouldBeTransformedToArray = true;

    protected $jsonContainVariadicType = false;

    protected $useNewMapper = true;

    /**
     * @param string $topic
     *
     * @return $this
     */
    public function setTopic(string $topic)
    {
        $this->payload['topic'] = $topic;

        return $this;
    }

    /**
     * @param float $creativity_index
     *
     * @return $this
     */
    public function setCreativityIndex(float $creativity_index)
    {
        $this->payload['creativity_index'] = $creativity_index;

        return $this;
    }

    /**
     * @return ContentGenerationGenerateSubTopicsLiveEntityMain
     */
    #[\Override]
    public function get(): ContentGenerationGenerateSubTopicsLiveEntityMain
    {
        return parent::get(); // TODO: Change the autogenerated stub
    }
}
