<?php

namespace DFSClientV3\Models\ContentGenerationApi;

use DFSClientV3\Entity\Custom\ContentGenerationTextSummaryLanguagesEntityMain;
use DFSClientV3\Models\AbstractModel;

class ContentGenerationTextSummaryLanguages extends AbstractModel
{
    protected $method = 'GET';

    protected $isSupportedMerge = false;

    protected $pathToMainData = 'tasks->{$postID}->result';

    protected $requestToFunction = 'content_generation/text_summary/languages';

    protected $resultShouldBeTransformedToArray = true;

    /**
     * @return ContentGenerationTextSummaryLanguagesEntityMain
     */
    #[\Override]
    public function get(): ContentGenerationTextSummaryLanguagesEntityMain
    {
        return parent::get(); // TODO: Change the autogenerated stub
    }
}
