<?php

namespace DFSClientV3\Models\ContentGenerationApi;

use DFSClientV3\Entity\Custom\ContentGenerationParaphraseLiveEntityMain;

class ContentGenerationParaphraseLive extends \DFSClientV3\Models\AbstractModel {

	protected $method = 'POST';
	protected $isSupportedMerge = true;
	protected $pathToMainData = 'tasks->{$postID}->result';
	protected $requestToFunction = 'content_generation/paraphrase/live';
	protected $resultShouldBeTransformedToArray = true;
	protected $jsonContainVariadicType = false;
	protected $useNewMapper = true;


	/**
	 * @param string $text
	 * @return $this
	 */
	public function setText(string $text) {
		$this->payload['text'] = $text;

		return $this;
	}

	/**
	 * @param float $creativity_index
	 * @return $this
	 */
	public function setCreativityIndex(float $creativity_index) {
		$this->payload['creativity_index'] = $creativity_index;

		return $this;
	}

	/**
	 * @param string $supplement_token
	 * @return $this
	 */
	public function setSupplementToken(string $supplement_token) {
		$this->payload['supplement_token'] = $supplement_token;

		return $this;
	}

	/**
	 * @return ContentGenerationParaphraseLiveEntityMain
	 */
	public function get(): ContentGenerationParaphraseLiveEntityMain
	{
		return parent::get(); // TODO: Change the autogenerated stub
	}
}
