<?php

namespace DFSClientV3\Models\ContentGenerationApi;

use DFSClientV3\Entity\Custom\ContentGenerationCheckGrammarLanguagesEntityMain;

class ContentGenerationCheckGrammarLanguages extends \DFSClientV3\Models\AbstractModel {

	protected $method = 'GET';
	protected $isSupportedMerge = false;
	protected $pathToMainData = 'tasks->{$postID}->result';
	protected $requestToFunction = 'content_generation/check_grammar/languages';
	protected $resultShouldBeTransformedToArray = true;

	/**
	 * @return ContentGenerationCheckGrammarLanguagesEntityMain
	 */
	public function get(): ContentGenerationCheckGrammarLanguagesEntityMain
	{
		return parent::get(); // TODO: Change the autogenerated stub
	}

}
