<?php

namespace DFSClientV3\Models\BusinessDataApi;

use DFSClientV3\Models\AbstractModel;

class BusinessUpdatesSettingTasks extends AbstractModel
{
    protected $method = 'POST';
    protected $isSupportedMerge = true;
    protected $pathToMainData = 'tasks->{$postID}->result';
    protected $requestToFunction = 'business_data/{$se}/my_business_updates/task_post';
    protected $resultShouldBeTransformedToArray = true;
    protected $useNewMapper = true;

	/**
	 * @param string $keyword
	 * @return $this
	 */
	public function setKeyword(string $keyword) {
		$this->payload['keyword'] = $keyword;
		return $this;
	}

	/**
	 * @param string $languageName
	 * @return $this
	 */
	public function setLanguageName(string $languageName) {
		$this->payload['language_name'] = $languageName;
		return $this;
	}

	/**
	 * @param string $langCode
	 * @return $this
	 */
	public function setLanguageCode(string $langCode) {
		$this->payload['language_code'] = $langCode;
		return $this;
	}

	/**
	 * @param string $locationName
	 * @return $this
	 */
	public function setLocationName(string $locationName) {
		$this->payload['location_name'] = $locationName;
		return $this;
	}

	/**
	 * @param int $locationCode
	 * @return $this
	 */
	public function setLocationCode(int $locationCode) {
		$this->payload['location_code'] = $locationCode;
		return $this;
	}

	/**
	 * @param string $locationCoordinate
	 * @return $this
	 */
	public function setLocationCoordinate(string $locationCoordinate) {
		$this->payload['location_coordinate'] = $locationCoordinate;
		return $this;
	}

	/**
	 * @param int $depth
	 * @return $this
	 */
	public function setDepth(int $depth) {
		$this->payload['depth'] = $depth;
		return $this;
	}

	/**
	 * @param string $priority
	 * @return $this
	 */
	public function setPriority(string $priority) {
		$this->payload['priority'] = $priority;
		return $this;
	}

	/**
	 * @param string $tag
	 * @return $this
	 */
	public function setTag(string $tag) {
		$this->payload['tag'] = $tag;
		return $this;
	}

	/**
	 * @param string $postbackUrl
	 * @return $this
	 */
	public function setPostbackUrl(string $postbackUrl) {
		$this->payload['postback_url'] = $postbackUrl;
		return $this;
	}

	/**
	 * @param string $postbackData
	 * @return $this
	 */
	public function setPostbackData(string $postbackData) {
		$this->payload['postback_data'] = $postbackData;
		return $this;
	}

	/**
	 * @param string $pingbackUrl
	 * @return $this
	 */
	public function setPingbackUrl(string $pingbackUrl) {
		$this->payload['pingback_url'] = $pingbackUrl;
		return $this;
	}

	/**
	 * @param string $seName
	 * @return $this
	 */
	public function setSe(string $seName) {
		$this->requestToFunction = str_replace('{$se}', $seName, $this->requestToFunction);
		return $this;
	}

	/**
	 * @param array $modelPool
	 * @return array
	 * @throws \Exception
	 */
	public static function getAfterMerge(array $modelPool) {
		return parent::getAfterMerge($modelPool); // TODO: Change the autogenerated stub
	}
}
