<?php


namespace DFSClientV3\Models\KeywordsDataApi\Keyword_Suggestions_For_Url;


use DFSClientV3\Models\AbstractModel;

class KeywordSuggestionsForUrlSetTask extends AbstractModel
{
    protected $method = 'POST';
    protected $isSupportedMerge = true;
    protected $pathToMainData = 'tasks->{$postID}->result';
    protected $requestToFunction = 'keywords_data/{$se}/keyword_suggestions_for_url/task_post';
    protected $resultShouldBeTransformedToArray = false;

	/**
	 * @param string $target
	 * @return $this
	 */
	public function setTarget(string $target)
	{
		$this->payload['target'] = $target;
		return $this;
	}

	/**
	 * @param string $languageName
	 * @return $this
	 */
	public function setLanguageName(string $languageName)
	{
		$this->payload['language_name'] = $languageName;
		return $this;
	}

	/**
	 * @param string $languageCode
	 * @return $this
	 */
	public function setLanguageCode(string $languageCode)
	{
		$this->payload['language_code'] = $languageCode;

		return $this;
	}

	/**
	 * @param bool $excludeBrands
	 * @return $this
	 */
	public function setExcludeBrands(bool $excludeBrands)
	{
		$this->payload['exclude_brands'] = $excludeBrands;
		return $this;
	}

	/**
	 * @param string $postbackUrl
	 * @return $this
	 */
	public function setPostbackUrl(string $postbackUrl)
	{
		$this->payload['postback_url'] = $postbackUrl;
		return $this;
	}

	/**
	 * @param string $pingbackUrl
	 * @return $this
	 */
	public function setPingbackUrl(string $pingbackUrl)
	{
		$this->payload['pingback_url'] = $pingbackUrl;
		return $this;
	}

	/**
	 * @param string $tag
	 * @return $this
	 */
	public function setTag(string $tag)
	{
		$this->payload['tag'] = $tag;
		return $this;
	}

	/**
	 * 'bing' only
	 * @param string $seName
	 * @return $this
	 */
	public function setSe(string $seName)
	{
		$this->requestToFunction = str_replace('{$se}', $seName, $this->requestToFunction);
		return $this;
	}

	/**
	 * @return \DFSClientV3\Entity\Custom\KeywordSuggestionsForUrlSetTaskEntityMain
	 */
	public function get(): \DFSClientV3\Entity\Custom\KeywordSuggestionsForUrlSetTaskEntityMain
	{
		return parent::get();
	}

	/**
	 * @param array $modelPool
	 * @return array
	 * @throws \Exception
	 */
	public static function getAfterMerge(array $modelPool)
	{
		return parent::getAfterMerge($modelPool); // TODO: Change the autogenerated stub
	}

}
