<?php

namespace DFSClientV3\Models\BacklinksApi;

use DFSClientV3\Entity\Custom\BackLinksTimeseriesNewLostSummaryEntityMain;
use DFSClientV3\Models\AbstractModel;

class BackLinksTimeseriesNewLostSummary extends AbstractModel
{
    protected $method = 'POST';
    protected $isSupportedMerge = false;
    protected $pathToMainData = 'tasks->{$postID}->result';
    protected $requestToFunction = 'backlinks/timeseries_new_lost_summary/live';
	protected $resultShouldBeTransformedToArray = true;
	protected $useNewMapper = true;

    /**
     * @param string $target
     * @return $this
     */
    public function setTarget(string $target)
    {
        $this->payload['target'] = $target;
        return $this;
    }

	/**
	 * @param string $groupRange
	 * @return $this
	 */
	public function setGroupRange(string $groupRange)
	{
		$this->payload['group_range'] = $groupRange;
		return $this;
	}

	/**
	 * @param string $dateFrom
	 * @return $this
	 */
	public function setDateFrom(string $dateFrom)
	{
		$this->payload['date_from'] = $dateFrom;
		return $this;
	}

	/**
	 * @param string $dateTo
	 * @return $this
	 */
	public function setDateTo(string $dateTo)
	{
		$this->payload['date_to'] = $dateTo;
		return $this;
	}

	/**
	 * @param string $tag
	 * @return $this
	 */
	public function setTag(string $tag)
	{
		$this->payload['tag'] = $tag;

		return $this;
	}

	/**
	 * @return BackLinksTimeseriesNewLostSummaryEntityMain
	 */
	public function get(): BackLinksTimeseriesNewLostSummaryEntityMain
	{
		return parent::get(); // TODO: Change the autogenerated stub
	}

}
