<?php


namespace DFSClientV3\Models\BacklinksApi;

use DFSClientV3\Entity\Custom\BacklinksBulkNewLostBacklinksEntityMain;
use DFSClientV3\Models\AbstractModel;

class BacklinksBulkNewLostBacklinks extends AbstractModel {
	protected $method = 'POST';
	protected $isSupportedMerge = true;
	protected $pathToMainData = 'tasks->{$postID}->result';
	protected $requestToFunction = 'backlinks/bulk_new_lost_backlinks/live';
	protected $resultShouldBeTransformedToArray = true;

	protected $jsonContainVariadicType = true;

	protected $pathsToVariadicTypesAndValue = [
		'tasks->(:number)->result->(:number)->items->(:number)' => 'type'
	];

	protected $useNewMapper = true;

	/**
	 * @param array $targets
	 * @return $this
	 */
	public function setTargets(array $targets) {
		$this->payload['targets'] = $targets;
		return $this;
	}

	/**
	 * @param string $dateAt
	 * @return $this
	 */
	public function setDateFrom(string $dateAt)
	{
		$this->payload['date_from'] = $dateAt;
		return $this;
	}

	/**
	 * @return BacklinksBulkNewLostBacklinksEntityMain
	 */
	public function get(): BacklinksBulkNewLostBacklinksEntityMain {
		return parent::get(); // TODO: Change the autogenerated stub
	}
}
