<?php

namespace DFSClientV3\Models\BusinessDataApi\BusinessListing;

use DFSClientV3\Entity\Custom\BusinessListingsSearchLiveEntityMain;
use DFSClientV3\Models\AbstractModel;

class BusinessListingsSearchLive extends AbstractModel
{
    protected $method = 'POST';

    protected $isSupportedMerge = true;

    protected $pathToMainData = 'tasks->{$postID}->result';

    protected $requestToFunction = 'business_data/business_listings/search/live';

    protected $resultShouldBeTransformedToArray = true;

    protected $jsonContainVariadicType = false;

    protected $pathsToVariadicTypesAndValue = ['tasks->(:number)->result->(:number)->items->(:number)' => 'type'];

    protected $useNewMapper = true;

    /**
     * @param array $categories
     *
     * @return $this
     */
    public function setCategories(array $categories)
    {
        $this->payload['categories'] = $categories;

        return $this;
    }

    /**
     * @param string $description
     *
     * @return $this
     */
    public function setDescription(string $description)
    {
        $this->payload['description'] = $description;

        return $this;
    }

    /**
     * @param string $title
     *
     * @return $this
     */
    public function setTitle(string $title)
    {
        $this->payload['title'] = $title;

        return $this;
    }

    /**
     * @param bool $is_claimed
     *
     * @return $this
     */
    public function setIsClaimed(bool $is_claimed)
    {
        $this->payload['is_claimed'] = $is_claimed;

        return $this;
    }

    /**
     * @param string $location_coordinate
     *
     * @return $this
     */
    public function setLocationCoordinate(string $location_coordinate)
    {
        $this->payload['location_coordinate'] = $location_coordinate;

        return $this;
    }

    /**
     * @param array $filters
     *
     * @return $this
     */
    public function setFilters(array $filters)
    {
        $this->payload['filters'] = $filters;

        return $this;
    }

    /**
     * @param array $orderBy
     *
     * @return $this
     */
    public function setOrderBy(array $orderBy)
    {
        $this->payload['order_by'] = $orderBy;

        return $this;
    }

    /**
     * @param int $limit
     *
     * @return $this
     */
    public function setLimit(int $limit)
    {
        $this->payload['limit'] = $limit;

        return $this;
    }

    /**
     * @param int $offset
     *
     * @return $this
     */
    public function setOffset(int $offset)
    {
        $this->payload['offset'] = $offset;

        return $this;
    }

    /**
     * @param string $offsetToken
     *
     * @return $this
     */
    public function setOffsetToken(string $offsetToken)
    {
        $this->payload['offset_token'] = $offsetToken;

        return $this;
    }

    /**
     * @param string $tag
     *
     * @return $this
     */
    public function setTag(string $tag)
    {
        $this->payload['tag'] = $tag;

        return $this;
    }

    #[\Override]
    protected function initCustomFunctionForPaths(): array
    {
        return [
            'tasks->(:number)->result->(:number)->items->(:number)->attributes->available_attributes'   => fn ($key, $value) => (array) $value,
            'tasks->(:number)->result->(:number)->items->(:number)->attributes->unavailable_attributes' => fn ($key, $value) => (array) $value,
            'tasks->(:number)->result->(:number)->items->(:number)->place_topics'                       => fn ($key, $value) => (array) $value,
        ];
    }

    /**
     * @return BusinessListingsSearchLiveEntityMain
     */
    #[\Override]
    public function get(): BusinessListingsSearchLiveEntityMain
    {
        return parent::get();
    }

    /**
     * @param array $modelPool
     *
     * @throws \Exception
     *
     * @return array
     */
    #[\Override]
    public static function getAfterMerge(array $modelPool)
    {
        return parent::getAfterMerge($modelPool); // TODO: Change the autogenerated stub
    }
}
