<?php

namespace DFSClientV3\Models\AiOptimizationApi\LlmMentions;

use DFSClientV3\Models\AbstractModel;

class LlmMentionsTopPagesLive extends AbstractModel {
	protected $method = 'POST';
	protected $isSupportedMerge = true;
	protected $pathToMainData = 'tasks->{$postID}->result';
	protected $requestToFunction = 'ai_optimization/llm_mentions/top_pages/live';
	protected $resultShouldBeTransformedToArray = true;
	protected $useNewMapper = true;

	public function setTarget(array $target) {
		$this->payload['target'] = $target;
		return $this;
	}

	/**
	 * @param string $locationName
	 * @return $this
	 */
	public function setLocationName(string $locationName) {
		$this->payload['location_name'] = $locationName;
		return $this;
	}

	/**
	 * @param string $languageName
	 * @return $this
	 */
	public function setLanguageName(string $languageName) {
		$this->payload['language_name'] = $languageName;
		return $this;
	}

	/**
	 * @param string $languageCode
	 * @return $this
	 */
	public function setLanguageCode(string $languageCode) {
		$this->payload['language_code'] = $languageCode;
		return $this;
	}

	/**
	 * @param int $locationCode
	 * @return $this
	 */
	public function setLocationCode(int $locationCode) {
		$this->payload['location_code'] = $locationCode;
		return $this;
	}

	/**
	 * @param string $platform
	 * @return $this
	 */
	public function setPlatform(string $platform) {
		$this->payload['platform'] = $platform;
		return $this;
	}

	/**
	 * @param string $linksScope
	 * @return $this
	 */
	public function setLinksScope(string $linksScope) {
		$this->payload['links_scope'] = $linksScope;
		return $this;
	}

	/**
	 * @param array $filters
	 * @return $this
	 */
	public function setInitialDatasetFilters(array $filters) {
		$this->payload['initial_dataset_filters'] = $filters;
		return $this;
	}

	/**
	 * @param int $internalListLimit
	 * @return $this
	 */
	public function setInternalListLimit(int $internalListLimit) {
		$this->payload['internal_list_limit'] = $internalListLimit;
		return $this;
	}

	/**
	 * @param int $itemsListLimit
	 * @return $this
	 */
	public function setItemsListLimit(int $itemsListLimit) {
		$this->payload['items_list_limit'] = $itemsListLimit;
		return $this;
	}

	/**
	 * @param string $tag
	 * @return $this
	 */
	public function setTag(string $tag) {
		$this->payload['tag'] = $tag;
		return $this;
	}

	/**
	 * @param array $modelPool
	 * @return array
	 * @throws \Exception
	 */
	public static function getAfterMerge(array $modelPool) {
		return parent::getAfterMerge($modelPool); // TODO: Change the autogenerated stub
	}

	/**
	 * @return \DFSClientV3\Entity\Custom\LlmMentionsTopPagesLiveEntityMain
	 */
	public function get(): \DFSClientV3\Entity\Custom\LlmMentionsTopPagesLiveEntityMain {
		return parent::get();
	}
}
