<?php

namespace DFSClientV3\Models\AiOptimizationApi\LlmMentions;

use DFSClientV3\Models\AbstractModel;

class LlmMentionsSearchLive extends AbstractModel {
	protected $method = 'POST';
	protected $isSupportedMerge = true;
	protected $pathToMainData = 'tasks->{$postID}->result';
	protected $requestToFunction = 'ai_optimization/llm_mentions/search/live';
	protected $resultShouldBeTransformedToArray = true;
	protected $useNewMapper = true;

	public function setTarget(array $target) {
		$this->payload['target'] = $target;
		return $this;
	}

	/**
	 * @param string $locationName
	 * @return $this
	 */
	public function setLocationName(string $locationName) {
		$this->payload['location_name'] = $locationName;
		return $this;
	}

	/**
	 * @param string $languageName
	 * @return $this
	 */
	public function setLanguageName(string $languageName) {
		$this->payload['language_name'] = $languageName;
		return $this;
	}

	/**
	 * @param string $languageCode
	 * @return $this
	 */
	public function setLanguageCode(string $languageCode) {
		$this->payload['language_code'] = $languageCode;
		return $this;
	}

	/**
	 * @param int $locationCode
	 * @return $this
	 */
	public function setLocationCode(int $locationCode) {
		$this->payload['location_code'] = $locationCode;
		return $this;
	}

	/**
	 * @param string $platform
	 * @return $this
	 */
	public function setPlatform(string $platform) {
		$this->payload['platform'] = $platform;
		return $this;
	}

	/**
	 * @param array $filters
	 * @return $this
	 */
	public function setFilters(array $filters) {
		$this->payload['filters'] = $filters;
		return $this;
	}

	/**
	 * @param array $orderBy
	 * @return $this
	 */
	public function setOrderBy(array $orderBy) {
		$this->payload['order_by'] = $orderBy;
		return $this;
	}

	/**
	 * @param int $limit
	 * @return $this
	 */
	public function setLimit(int $limit) {
		$this->payload['limit'] = $limit;
		return $this;
	}

	/**
	 * @param int $offset
	 * @return $this
	 */
	public function setOffset(int $offset) {
		$this->payload['offset'] = $offset;
		return $this;
	}

	/**
	 * @param string $search_after_token
	 * @return $this
	 */
	public function setSearchAfterToken(string $search_after_token)
	{
		$this->payload['search_after_token'] = $search_after_token;
		return $this;
	}

	/**
	 * @param string $tag
	 * @return $this
	 */
	public function setTag(string $tag) {
		$this->payload['tag'] = $tag;
		return $this;
	}

	/**
	 * @param array $modelPool
	 * @return array
	 * @throws \Exception
	 */
	public static function getAfterMerge(array $modelPool) {
		return parent::getAfterMerge($modelPool); // TODO: Change the autogenerated stub
	}

	/**
	 * @return \DFSClientV3\Entity\Custom\LLmmentionsSearchLiveEntityMain
	 */
	public function get(): \DFSClientV3\Entity\Custom\LLmmentionsSearchLiveEntityMain {
		return parent::get();
	}
}
