<?php

namespace DFSClient\Models\SERP_API;

use DFSClient\Models\AbstractModel;
use function GuzzleHttp\Psr7\str;

class GetSerpCompletedTasks extends AbstractModel
{
    protected $method = 'GET';
    protected $isSupportedMerge = false;
    protected $pathToMainData = 'tasks->{$postID}->result';
    protected $requestToFunction = 'serp/{$se}/{$seType}/tasks_ready';
    protected $resultShouldBeTransformedToArray = false;

    /**
     * @var null
     */
    private  $se = null;

    /**
     * @var null
     */
    private  $seType = null;

//    public function setTaskId(string $taskUID)
//    {
//        $this->requestToFunction = str_replace('{$taskUID}', $taskUID, $this->requestToFunction);
//        return $this;
//    }
    /**
     * @param string $seType
     * @return $this
     * @throws \Exception
     */
    public function setSeType(string $seType)
    {
        if (!in_array($seType,$this->seTypes))
            throw new \Exception('Provided se type not allowed');

        $this->seType = $seType;

        $this->requestToFunction = str_replace('{$seType}', $seType, $this->requestToFunction);

        return $this;
    }

    /**
     * @param string $seName
     * @return $this
     */
    public function setSe(string $seName)
    {
        $this->se = $seName;
        $this->requestToFunction = str_replace('{$se}', $seName, $this->requestToFunction);
        return $this;
    }

    /**
     * @return \DFSClient\Entity\Custom\GetSerpCompletedTasksEntityMain
     */
    public function get(): \DFSClient\Entity\Custom\GetSerpCompletedTasksEntityMain
    {
        return parent::get();
    }

    /**
     * @return \DFSClient\Services\HttpClient\Handlers\Responses
     */
    public function process()
    {

        if ($this->seType === null or $this->se === null)
            $this->requestToFunction = str_replace('/{$se}/{$seType}','', $this->requestToFunction);

        return parent::process(); // TODO: Change the autogenerated stub
    }
}
