<?php

namespace DFSClientV3\Models\DataForSeoLabsApi\Bing;

use DFSClientV3\Entity\Custom\BingBulkKeywordDifficultyLiveEntityMain;
use DFSClientV3\Models\AbstractModel;

class BingBulkKeywordDifficultyLive extends AbstractModel
{
    protected $method = 'POST';

    protected $isSupportedMerge = true;

    protected $pathToMainData = 'tasks->{$postID}->result';

    protected $requestToFunction = 'dataforseo_labs/bing/bulk_keyword_difficulty/live';

    protected $resultShouldBeTransformedToArray = true;

    /**
     * @return BingBulkKeywordDifficultyLiveEntityMain
     */
    #[\Override]
    public function get(): BingBulkKeywordDifficultyLiveEntityMain
    {
        return parent::get();
    }

    /**
     * @param array $targets
     *
     * @return $this
     */
    public function setKeywords(array $keywords)
    {
        $this->payload['keywords'] = $keywords;

        return $this;
    }

    /**
     * @param string $locationName
     *
     * @return $this
     */
    public function setLocationName(string $locationName)
    {
        $this->payload['location_name'] = $locationName;

        return $this;
    }

    /**
     * @param int $locationCode
     *
     * @return $this
     */
    public function setLocationCode(int $locationCode)
    {
        $this->payload['location_code'] = $locationCode;

        return $this;
    }

    /**
     * @param string $languageName
     *
     * @return $this
     */
    public function setLanguageName(string $languageName)
    {
        $this->payload['language_name'] = $languageName;

        return $this;
    }

    /**
     * @param string $languageCode
     *
     * @return $this
     */
    public function setLanguageCode(string $languageCode)
    {
        $this->payload['language_code'] = $languageCode;

        return $this;
    }

    /**
     * @param array $modelPool
     *
     * @throws \Exception
     *
     * @return array
     */
    #[\Override]
    public static function getAfterMerge(array $modelPool)
    {
        return parent::getAfterMerge($modelPool); // TODO: Change the autogenerated stub
    }
}
