<?php


namespace DFSClientV3\Models\OnPageApi;

use DFSClientV3\Entity\Custom\OnPagePageScreenshotEntityMain;
use DFSClientV3\Models\AbstractModel;

class OnPagePageScreenshot extends AbstractModel
{
    protected $method = 'POST';
    protected $isSupportedMerge = true;
    protected $pathToMainData = 'tasks->{$postID}->result';
    protected $requestToFunction = 'on_page/page_screenshot';
    protected $resultShouldBeTransformedToArray = false;


    /**
     * @param string $url
     * @return $this
     */
    public function setUrl(string $url)
    {
      $this->payload['url'] = $url;
      return $this;
    }

	/**
	 * @param string $acceptLanguage
	 * @return $this
	 */
	public function setAcceptLanguage(string $acceptLanguage)
	{
		$this->payload['accept_language'] = $acceptLanguage;
		return $this;
	}

    /**
     * @param bool $enableJavascript
     * @return $this
     */
    public function setEnableJavascript(bool $enableJavascript)
    {
        $this->payload['enable_javascript'] = $enableJavascript;
        return $this;
    }

	/**
	 * @param string $customJs
	 * @return $this
	 */
	public function setCustomJs(string $customJs)
	{
		$this->payload['custom_js'] = $customJs;
		return $this;
	}

    /**
     * @param array $modelPool
     * @return OnPagePageScreenshotEntityMain
     * @throws \Exception
     */
    public static function getAfterMerge(array $modelPool): OnPagePageScreenshotEntityMain
    {
        return parent::getAfterMerge($modelPool); // TODO: Change the autogenerated stub
    }

}
