<?php


namespace DFSClientV3\Models\OnPageApi;


use DFSClientV3\Entity\Custom\OnPageGetWaterfallEntityMain;
use DFSClientV3\Models\AbstractModel;

class OnPageGetWaterfall extends AbstractModel
{
    protected $method = 'POST';
    protected $isSupportedMerge = false;
    protected $pathToMainData = 'tasks->0->result';
    protected $requestToFunction = 'on_page/waterfall';
    protected $resultShouldBeTransformedToArray = true;

    protected $useNewMapper = true;

    /**
     * @param string $taskID
     * @return $this
     */
    public function setTaskID(string $taskID)
    {
        $this->payload['id'] = $taskID;
        return $this;
    }

    /**
     * @param string $url
     * @return $this
     */
    public function setUrl(string $url)
    {
        $this->payload['url'] = $url;
        return $this;
    }

    /**
     * @param string $tag
     * @return $this
     */
    public function setTag(string $tag)
    {
        $this->payload['tag'] = $tag;
        return $this;
    }

    /**
     * @return OnPageGetWaterfallEntityMain
     */
    public function get(): OnPageGetWaterfallEntityMain
    {
        return parent::get(); // TODO: Change the autogenerated stub
    }
}
