<?php


namespace DFSClientV3\Models\BacklinksApi\Dictionaries;


use DFSClientV3\Entity\Custom\BackLinksDomainIntersectionEntityMainTasksResultItemsDomainIntersectionDictionaryItem;
use DFSClientV3\Entity\Custom\DictionaryEntity;

class DomainIntersectionDictionary extends DictionaryEntity
{
    /**
     * @param string $key
     * @return BackLinksDomainIntersectionEntityMainTasksResultItemsDomainIntersectionDictionaryItem
     */
    public function get(string $key): ?array
    {
        return parent::get($key); // TODO: Change the autogenerated stub
    }

    public function getAll(): array
    {
        return parent::getAll(); // TODO: Change the autogenerated stub
    }
}
