<?php

namespace DFSClientV3\Models\BacklinksApi\Dictionaries;

use DFSClientV3\Entity\Custom\BackLinksPageIntersectionEntityMainTasksResultItemsPageIntersectionDictionaryItem;
use DFSClientV3\Entity\Custom\DictionaryEntity;

class PageIntersectionDictionary extends DictionaryEntity
{
    /**
     * @param string $key
     *
     * @return array|null
     */
    #[\Override]
    public function get(string $key): ?array
    {
        return parent::get($key); // TODO: Change the autogenerated stub
    }

    #[\Override]
    public function getAll(): array
    {
        return parent::getAll(); // TODO: Change the autogenerated stub
    }
}
