<?php

namespace DFSClientV3\Models\DomainAnalyticsApi\Technologies;

use DFSClientV3\Models\AbstractModel;

class TechnologiesDomainsByTechnologyLive extends AbstractModel {
	protected $method = 'POST';
	protected $isSupportedMerge = true;
	protected $pathToMainData = 'tasks->{$postID}->result';
	protected $requestToFunction = 'domain_analytics/technologies/domains_by_technology/live';
	protected $resultShouldBeTransformedToArray = true;
	protected $useNewMapper = true;

	/**
	 * @return \DFSClientV3\Entity\Custom\TechnologiesDomainsByTechnologyLiveEntityMain
	 */
	public function get(): \DFSClientV3\Entity\Custom\TechnologiesDomainsByTechnologyLiveEntityMain {
		return parent::get();
	}

	/**
	 * @param array $keywords
	 * @return $this
	 */
	public function setKeywords(array $keywords) {
		$this->payload['keywords'] = $keywords;
		return $this;
	}

	/**
	 * @param array $groups
	 * @return $this
	 */
	public function setGroups(array $groups) {
		$this->payload['groups'] = $groups;
		return $this;
	}

	/**
	 * @param array $categories
	 * @return $this
	 */
	public function setCategories(array $categories) {
		$this->payload['categories'] = $categories;
		return $this;
	}

	/**
	 * @param array $technologies
	 * @return $this
	 */
	public function setTechnologies(array $technologies) {
		$this->payload['technologies'] = $technologies;
		return $this;
	}

	/**
	 * @param string $mode
	 * @return $this
	 */
	public function setMode(string $mode) {
		$this->payload['mode'] = $mode;
		return $this;
	}

	/**
	 * @param string $technologyPaths
	 * @return $this
	 */
	public function setTechnologyPaths(string $technologyPaths) {
		$this->payload['technology_paths'] = $technologyPaths;
		return $this;
	}

	/**
	 * @param array $filters
	 * @return $this
	 */
	public function setFilters(array $filters) {
		$this->payload['filters'] = $filters;
		return $this;
	}

	/**
	 * @param array $orderBy
	 * @return $this
	 */
	public function setOrderBy(array $orderBy) {
		$this->payload['order_by'] = $orderBy;
		return $this;
	}

	/**
	 * @param int $limit
	 * @return $this
	 */
	public function setLimit(int $limit) {
		$this->payload['limit'] = $limit;
		return $this;
	}

	/**
	 * @param int $offset
	 * @return $this
	 */
	public function setOffset(int $offset) {
		$this->payload['offset'] = $offset;
		return $this;
	}

	/**
	 * @param string $offsetToken
	 * @return $this
	 */
	public function setOffsetToken(string $offsetToken) {
		$this->payload['offset_token'] = $offsetToken;
		return $this;
	}

	/**
	 * @param string $tag
	 * @return $this
	 */
	public function setTag(string $tag) {
		$this->payload['tag'] = $tag;
		return $this;
	}

	/**
	 * @param array $modelPool
	 * @return array
	 * @throws \Exception
	 */
	public static function getAfterMerge(array $modelPool) {
		return parent::getAfterMerge($modelPool); // TODO: Change the autogenerated stub
	}
}
