<?php

namespace DFSClientV3\Models\DomainAnalyticsApi\Technologies;

use DFSClientV3\Models\AbstractModel;

class TechnologiesDomainTechnologiesLive extends AbstractModel {
	protected $method = 'POST';
	protected $isSupportedMerge = true;
	protected $pathToMainData = 'tasks->{$postID}->result';
	protected $requestToFunction = 'domain_analytics/technologies/domain_technologies/live';
	protected $resultShouldBeTransformedToArray = true;
	protected $useNewMapper = true;

	/**
	 * @return \DFSClientV3\Entity\Custom\TechnologiesDomainTechnologiesLiveEntityMain
	 */
	public function get(): \DFSClientV3\Entity\Custom\TechnologiesDomainTechnologiesLiveEntityMain {
		return parent::get();
	}

	/**
	 * @param string $target
	 * @return $this
	 */
	public function setTarget(string $target) {
		$this->payload['target'] = $target;
		return $this;
	}

	/**
	 * @param string $tag
	 * @return $this
	 */
	public function setTag(string $tag) {
		$this->payload['tag'] = $tag;
		return $this;
	}

	/**
	 * @param array $modelPool
	 * @return array
	 * @throws \Exception
	 */
	public static function getAfterMerge(array $modelPool) {
		return parent::getAfterMerge($modelPool); // TODO: Change the autogenerated stub
	}
}
