<?php

namespace DFSClientV3\Models\SerpApi;

use DFSClientV3\Entity\Custom\SerpScreenshotEntityMain;
use DFSClientV3\Models\AbstractModel;

class SerpScreenshot extends AbstractModel
{
    protected $method = 'POST';

    protected $isSupportedMerge = true;

    protected $pathToMainData = 'tasks->{$postID}->result';

    protected $requestToFunction = 'serp/screenshot';

    protected $resultShouldBeTransformedToArray = true;

    /**
     * @param string $taskId
     *
     * @return $this
     */
    public function setTaskId(string $taskId)
    {
        $this->payload['task_id'] = $taskId;

        return $this;
    }

    /**
     * @param int $page
     *
     * @return $this
     */
    public function setPage(int $page)
    {
        $this->payload['page'] = $page;

        return $this;
    }

    /**
     * @param string $device
     *
     * @return $this
     */
    public function setDevice(string $device)
    {
        $this->payload['device'] = $device;

        return $this;
    }

    /**
     * @param int $width
     *
     * @return $this
     */
    public function setWidth(int $width)
    {
        $this->payload['width'] = $width;

        return $this;
    }

    /**
     * @param int $height
     *
     * @return $this
     */
    public function setHeight(int $height)
    {
        $this->payload['height'] = $height;

        return $this;
    }

    /**
     * @param float $scaleFactor
     *
     * @return $this
     */
    public function setScaleFactor($scaleFactor)
    {
        $this->payload['scale_factor'] = $scaleFactor;

        return $this;
    }

    /**
     * @param string $tag
     *
     * @return $this
     */
    public function setTag(string $tag)
    {
        $this->payload['tag'] = $tag;

        return $this;
    }

    /**
     * @param array $modelPool
     *
     * @throws \Exception
     *
     * @return SerpScreenshotEntityMain
     */
    #[\Override]
    public static function getAfterMerge(array $modelPool): SerpScreenshotEntityMain
    {
        return parent::getAfterMerge($modelPool); // TODO: Change the autogenerated stub
    }
}
