<?php


namespace DFSClientV3\Models\KeywordsDataApi\ClickstreamData;


use DFSClientV3\Models\AbstractModel;

class ClickstreamBulkSearchVolumeLive extends AbstractModel
{
    protected $method = 'POST';
    protected $isSupportedMerge = true;
	protected $pathToMainData = 'tasks->{$postID}->result';
	protected $requestToFunction = 'keywords_data/clickstream_data/bulk_search_volume/live';
	protected $resultShouldBeTransformedToArray = true;
	protected $useNewMapper = true;

    /**
     * @return \DFSClientV3\Entity\Custom\ClickstreamBulkSearchVolumeLiveEntityMain
     */
    public function get(): \DFSClientV3\Entity\Custom\ClickstreamBulkSearchVolumeLiveEntityMain
    {
        return parent::get();
    }

    /**
     * @param array $keyword
     * @return $this
     */
    public function setKeywords(array $keywords)
    {
        $this->payload['keywords'] = $keywords;
        return $this;
    }

    /**
     * @param string $locationName
     * @return $this
     */
    public function setLocationName(string $locationName)
    {
        $this->payload['location_name'] = $locationName;
        return $this;
    }

    /**
     * @param int $locationCode
     * @return $this
     */
    public function setLocationCode(int $locationCode)
    {
        $this->payload['location_code'] = $locationCode;
        return $this;
    }

    /**
     * @param string $tag
     * @return $this
     */
    public function setTag(string $tag)
    {
        $this->payload['tag'] = $tag;
        return $this;
    }

    /**
     * @param array $modelPool
     * @return array
     * @throws \Exception
     */
    public static function getAfterMerge(array $modelPool)
    {
        return parent::getAfterMerge($modelPool); // TODO: Change the autogenerated stub
    }
}
