<?php

namespace DFSClientV3\Models\KeywordsDataApi\ClickstreamData;

use DFSClientV3\Entity\Custom\ClickstreamDataforseoSearchVolumeLiveEntityMain;
use DFSClientV3\Models\AbstractModel;

class ClickstreamDataforseoSearchVolumeLive extends AbstractModel
{
    protected $method = 'POST';

    protected $isSupportedMerge = true;

    protected $pathToMainData = 'tasks->{$postID}->result';

    protected $requestToFunction = 'keywords_data/clickstream_data/dataforseo_search_volume/live';

    protected $resultShouldBeTransformedToArray = true;

    protected $useNewMapper = true;

    /**
     * @return ClickstreamDataforseoSearchVolumeLiveEntityMain
     */
    #[\Override]
    public function get(): ClickstreamDataforseoSearchVolumeLiveEntityMain
    {
        return parent::get();
    }

    /**
     * @param array $keyword
     *
     * @return $this
     */
    public function setKeywords(array $keywords)
    {
        $this->payload['keywords'] = $keywords;

        return $this;
    }

    /**
     * @param string $locationName
     *
     * @return $this
     */
    public function setLocationName(string $locationName)
    {
        $this->payload['location_name'] = $locationName;

        return $this;
    }

    /**
     * @param int $locationCode
     *
     * @return $this
     */
    public function setLocationCode(int $locationCode)
    {
        $this->payload['location_code'] = $locationCode;

        return $this;
    }

    /**
     * @param string $languageName
     *
     * @return $this
     */
    public function setLanguageName(string $languageName)
    {
        $this->payload['language_name'] = $languageName;

        return $this;
    }

    /**
     * @param string $languageCode
     *
     * @return $this
     */
    public function setLanguageCode(string $languageCode)
    {
        $this->payload['language_code'] = $languageCode;

        return $this;
    }

    /**
     * @param bool $useClickstream
     *
     * @return $this
     */
    public function setUseClickstream(bool $useClickstream)
    {
        $this->payload['use_clickstream'] = $useClickstream;

        return $this;
    }

    /**
     * @param string $tag
     *
     * @return $this
     */
    public function setTag(string $tag)
    {
        $this->payload['tag'] = $tag;

        return $this;
    }

    /**
     * @param array $modelPool
     *
     * @throws \Exception
     *
     * @return array
     */
    #[\Override]
    public static function getAfterMerge(array $modelPool)
    {
        return parent::getAfterMerge($modelPool); // TODO: Change the autogenerated stub
    }
}
